version: "3"

services:
  postgres:
    image: postgres:alpine
    volumes:
      - database:/var/lib/postgresql/data
    ports:
      - 5432:5432
    environment:
      - POSTGRES_PASSWORD=postgres

volumes:
  database:
